#!/usr/bin/env bun
/**
 * Generates scripts/embedded.gen.ts — one `with { type: 'file' }` import per
 * built dist/ asset — so `bun build --compile` embeds the whole dashboard
 * inside the standalone executable (scripts/serve.ts). Run AFTER `bun run
 * build` and BEFORE compiling.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = join(import.meta.dir, '..', 'dist');
const files: string[] = [];

function walk(dir: string): void {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
}
walk(root);

let imports = '';
let entries = '';
files.forEach((f, i) => {
  const rel = relative(root, f).replaceAll('\\', '/');
  imports += `import f${i} from ${JSON.stringify(`../dist/${rel}`)} with { type: 'file' };\n`;
  entries += `  ${JSON.stringify(`/${rel}`)}: f${i},\n`;
});

writeFileSync(
  join(import.meta.dir, 'embedded.gen.ts'),
  `// AUTO-GENERATED by scripts/gen-embed.ts — do not edit, not committed.\n${imports}\nexport const ASSETS: Record<string, string> = {\n${entries}};\n`
);
console.log(`embedded ${files.length} dist assets → scripts/embedded.gen.ts`);
